import { br, div, main } from 'radipan/tags';
import Icon from './components/Icon';

function App() {
  return main.create(
    {
      css: {
        width: '100%',
        height: '100vh',
        color: { base: 'black', _osDark: 'white' },
        background: { base: 'white', _osDark: 'black' },
      },
    },
    [
      div.create(
        { css: { fontSize: '2xl', fontWeight: 'bold' } },
        'Hello Radip🐼n!'
      ),
      Icon.create({ name: 'arrow' }),
      Icon.create({ name: 'arrow-up' }),
      Icon.create({ name: 'arrow-left' }),
      Icon.create({ name: 'arrow-back' }),
      Icon.create({ name: 'arrow-right' }),
      Icon.create({ name: 'arrow-forward' }),
      Icon.create({ name: 'backspace' }),
      Icon.create({ name: 'ban' }),
      Icon.create({ name: 'caret-left' }),
      Icon.create({ name: 'caret-right' }),
      Icon.create({ name: 'caret-up' }),
      Icon.create({ name: 'caret-down' }),
      Icon.create({ name: 'caret-forward' }),
      Icon.create({ name: 'caret-back' }),
      Icon.create({ name: 'checkmark' }),
      Icon.create({ name: 'check' }),
      Icon.create({ name: 'checkmark-double' }),
      Icon.create({ name: 'check-double' }),
      Icon.create({ name: 'checkmark-done' }),
      Icon.create({ name: 'check-done' }),
      Icon.create({ name: 'menu' }),
      Icon.create({ name: 'chevron-up' }),
      Icon.create({ name: 'chevron-down' }),
      Icon.create({ name: 'chevron-left' }),
      Icon.create({ name: 'chevron-right' }),
      Icon.create({ name: 'chevron' }),
      Icon.create({ name: 'chevron-forward' }),
      Icon.create({ name: 'chevron-back' }),
      Icon.create({ name: 'chevron-collapse' }),
      Icon.create({ name: 'chevron-expand' }),
      Icon.create({ name: 'close' }),
      Icon.create({ name: 'x' }),
      Icon.create({ name: 'ellipsis' }),
      Icon.create({ name: 'ellipsis-horizontal' }),
      Icon.create({ name: 'ellipsis-vertical' }),
      Icon.create({ name: 'help' }),
      Icon.create({ name: '?' }),
      Icon.create({ name: 'question-mark' }),
      Icon.create({ name: 'i' }),
      Icon.create({ name: 'info' }),
      Icon.create({ name: 'information' }),
      Icon.create({ name: '!' }),
      Icon.create({ name: 'alert' }),
      Icon.create({ name: 'link' }),
      Icon.create({ name: 'unlink' }),
      Icon.create({ name: 'move' }),
      Icon.create({ name: 'person' }),
      Icon.create({ name: 'pause' }),
      Icon.create({ name: 'refresh' }),
      Icon.create({ name: 'reload' }),
      Icon.create({ name: 'add' }),
      Icon.create({ name: 'plus' }),
      Icon.create({ name: '+' }),
      Icon.create({ name: 'remove' }),
      Icon.create({ name: 'minus' }),
      Icon.create({ name: '-' }),
      br.create(),
      Icon.create({ name: 'warning' }),
      Icon.create({ name: 'warning-circle' }),
      Icon.create({ name: 'alert-circle' }),
      Icon.create({ name: 'check-circle' }),
      Icon.create({ name: 'checkmark-circle' }),
      Icon.create({ name: 'checkbox' }),
      Icon.create({ name: 'checkmark-double-circle' }),
      Icon.create({ name: 'checkmark-done-circle' }),
      Icon.create({ name: 'check-double-circle' }),
      Icon.create({ name: 'check-done-circle' }),
      Icon.create({ name: 'close-circle' }),
      Icon.create({ name: 'x-circle' }),
      Icon.create({ name: 'ellipsis-circle' }),
      Icon.create({ name: 'ellipsis-horizontal-circle' }),
    ]
  );
}

export default App;
